env: CartPole-v1                                                  # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 100
freqOptim: 1                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 50000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 300  
gamma: 0.99
nbTr : 1
C : 10
mem_size : 1000
mbs : 1000
ActorLr : 0.001
ValueLr : 0.001
ActorLayers : [30, 30]
ValueLayers : [30, 30]


