env: LunarLander-v2
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 10
freqOptim: 1                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 50000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 100  

gamma: 0.999
nbTr : 1
C : 10
K : 10
delta : 0.1

mem_size : 10000
mbs : 1000

ActorLr : 0.0003
ValueLr : 0.0003
DiscLr : 0.0003
ActorLayers : [120, 120]
ValueLayers : [120, 120]
DiscLayers : [120, 120]

epsilon : 0.2
entWeight : 0.01
rewards : 'pos'
eps_d : 0.0001
algo : 'clipped'
sigma : 0.01
